title: Parjita Munshi
logo: 
  <p align="center">
  <img src="/images/profile_photo.png" alt="Profile Photo" width="200" height="200" style="border-radius: 50%;">
  </p>"/images/profile_photo.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science | Machine Learning | Data Analysis | Software Engineering <br>
  <a href="mailto:parjita.munshi04@gmail.com">âœ‰ï¸ Email</a><br>
  <a href="https://www.linkedin.com/in/parjitamunshi/">ğŸ”— LinkedIn</a><br>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme



