title: Parjita Munshi
logo: "/images/profile_photo.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
  An explorer,
  <br><br>
  A Problem Solver
  <br><br>
  A researcher
  <br><br>  
  âœ‰ï¸ Email: [parjita.munshi04@gmail.com](mailto:parjita.munshi04@gmail.com) 
  <br><br>
  ğŸ”— [LinkedIn](https://www.linkedin.com/in/parjitamunshi/)
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme



