title: Parjita Munshi
logo: "/images/profile_photo.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
  An explorer,
  A Problem Solver
  A researcher
  <br><br>  
  <a href="mailto:parjita.munshi04@gmail.com"> âœ‰ï¸ Email: </a>
  <a href="https://www.linkedin.com/in/parjitamunshi/> ğŸ”— LinedIn: </a>
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme



